apiVersion: v1
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  nginx;

        location /node3/ {
            proxy_pass http://10.1.0.61:7900/;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_http_version 1.1;
        }
        location /node2/ {
            proxy_pass http://10.1.0.56:7900/;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_http_version 1.1;
        }
        location /node1/ {
            proxy_pass http://10.1.0.53:7900/;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_http_version 1.1;
        }          
    }  
kind: ConfigMap
metadata:
  name: nginx
  namespace: default
