apiVersion: v1
kind: Service
metadata:
  labels:
    app: selenium-node-firefox
  name: selenium-node-firefox
  namespace: default
spec:
  ports:
  - port: 7900
    protocol: TCP
    name: webview  
  selector:
    app: selenium-node-firefox
  type: NodePort

