apiVersion: v1
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  nginx;

        location / {
            proxy_pass http://10.1.0.53:7900/;

            if ($http_upgrade = "websocket") {
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }
        }  
    }  
kind: ConfigMap
metadata:
  name: nginx
  namespace: default
