apiVersion: v1
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  nginx;

        location / {
          proxy_pass http://10.1.0.53:7900/;
        }
    }  
kind: ConfigMap
metadata:
  name: nginx
  namespace: default
