apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: selenium-standalone-chrome
  name: selenium-standalone-chrome
  namespace: default
spec:
  selector:
    matchLabels:
      app: selenium-standalone-chrome
  template:
    metadata:
      labels:
        app: selenium-standalone-chrome
    spec:
      containers:
      - image: selenium/standalone-chrome:108.0
        imagePullPolicy: IfNotPresent
        name: standalone-chrome
