apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: selenium-standalone-edge
  name: selenium-standalone-edge
  namespace: default
spec:
  selector:
    matchLabels:
      app: selenium-standalone-edge
  template:
    metadata:
      labels:
        app: selenium-standalone-edge
    spec:
      containers:
      - image: selenium/standalone-edge:108.0
        imagePullPolicy: IfNotPresent
        name: standalone-edge
