apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: selenium-standalone-firefox
  name: selenium-standalone-firefox
  namespace: default
spec:
  selector:
    matchLabels:
      app: selenium-standalone-firefox
  template:
    metadata:
      labels:
        app: selenium-standalone-firefox
    spec:
      containers:
      - image: selenium/standalone-firefox:108.0
        imagePullPolicy: IfNotPresent
        name: standalone-firefox
        ports:
        - containerPort: 4444
          protocol: TCP
          name: webdriver
        - containerPort: 7900
          protocol: TCP
          name: webview
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2G
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2G          
