apiVersion: v1
kind: Service
metadata:
  labels:
    app: selenium-hub
  name: selenium-hub
  namespace: default
spec:
  ports:
  - port: 4444
    protocol: TCP
    name: webdriver
  - port: 4443
    protocol: TCP
    name: subscribe
  - port: 4442
    protocol: TCP
    name: publish    
  selector:
    app: selenium-hub
  type: NodePort

