apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: selenium-standalone-firefox
  name: selenium-standalone-firefox
  namespace: default
spec:
  selector:
    matchLabels:
      app: selenium-standalone-firefox
  template:
    metadata:
      labels:
        app: selenium-standalone-firefox
    spec:
      containers:
      - image: selenium/standalone-firefox:108.0
        imagePullPolicy: IfNotPresent
        name: standalone-firefox
        ports:
        - containerPort: 4444
          protocol: TCP
          name: webdriver
        - containerPort: 7900
          protocol: TCP
          name: webview
        resources:
          limits:
            cpu: 750m
            ephemeral-storage: 1Gi
            memory: 1G
          requests:
            cpu: 750m
            ephemeral-storage: 1Gi
            memory: 1G
        env:
        - name: SE_SCREEN_WIDTH
          value: '1920'
        - name: SE_SCREEN_HEIGHT
          value: '1080'
        - name: SE_NODE_MAX_SESSIONS
          value: '2'
